name: Build and Test

runs:
  using: composite
  steps:
    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 

    - name: Ensure everything is tidy
      shell: bash
      run: |
        bazelisk run //:tidy_check

    - name: Execute Integration Tests
      shell: bash
      run: |
        bazelisk test //:all_integration_tests
