load("@cgrindel_bazel_starlib//bzlformat:defs.bzl", "bzlformat_pkg")
load(
    "@cgrindel_bazel_starlib//bzlrelease:defs.bzl",
    "create_release",
    "generate_module_snippet",
    "generate_release_notes",
    "update_readme",
)

# MARK: - Release

generate_module_snippet(
    name = "generate_module_snippet",
    module_name = "rules_swift_tidy",
)

generate_release_notes(
    name = "generate_release_notes",
    generate_module_snippet = ":generate_module_snippet",
)

update_readme(
    name = "update_readme",
    generate_module_snippet = ":generate_module_snippet",
)

create_release(
    name = "create",
    workflow_name = "Create Release",
)

bzlformat_pkg(name = "bzlformat")
