workspace(name = "simple_example")

local_repository(
    name = "cgrindel_rules_swiftformat",
    path = "../..",
)

load(
    "@cgrindel_rules_swiftformat//swiftformat:deps.bzl",
    "swiftformat_rules_dependencies",
)

swiftformat_rules_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "@cgrindel_bazel_starlib//:deps.bzl",
    "bazel_starlib_dependencies",
)

bazel_starlib_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@cgrindel_rules_swiftformat//swiftformat:defs.bzl",
    "swiftformat_register_prebuilt_toolchains",
)

swiftformat_register_prebuilt_toolchains()
