name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:16 UTC.
    - cron: '16 11 * * *'

jobs:
  macos_build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0.1'
    - uses: ./.github/actions/build_and_test

  ubuntu_build:
    runs-on: ubuntu-22.04
    env:
      CC: clang
    steps:
    - uses: cgrindel/gha_install_swift_on_ubuntu@v1
      id: install_swift
      with:
        swift_release_tag: "swift-5.7.2-RELEASE"
        ubuntu_version: "22.04"
    - uses: actions/checkout@v3
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat
    - name: Update local.bazelrc with Linux Flags
      shell: bash
      run: |
        cat >> "local.bazelrc" <<EOF
        # Need to expose the PATH so that the Swift toolchain can be found
        build --action_env=PATH
        # Need to expose the LD_LIBRARY_PATH so that the Swift dynamic loaded 
        # so files can be found
        build --action_env=LD_LIBRARY_PATH
        EOF
    - uses: ./.github/actions/build_and_test

  all_ci_tests:
    runs-on: ubuntu-latest
    needs: [macos_build, ubuntu_build]
    steps:
      - name: All is Well
        shell: bash
        run: |
          echo "All is well!"

