name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat
    - uses: ./.github/actions/build_and_test

