name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 11:16 UTC.
    - cron: '16 11 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  macos_build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat
    # DEBUG BEGIN
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true
        wait-timeout-minutes: 5
    # DEBUG END
    - uses: ./.github/actions/build_and_test

  ubuntu_build:
    runs-on: ubuntu-22.04
    env:
      CC: clang
    steps:
    - uses: cgrindel/gha_install_swift_on_ubuntu@v1
      id: install_swift
      with:
        swift_release_tag: "swift-5.7.2-RELEASE"
        ubuntu_version: "22.04"
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat
    - name: Update local.bazelrc with Linux Flags
      shell: bash
      run: |
        cat >> "local.bazelrc" <<EOF
        # Need to expose the PATH so that the Swift toolchain can be found
        build --action_env=PATH
        # Need to expose the LD_LIBRARY_PATH so that the Swift dynamic loaded 
        # so files can be found
        build --action_env=LD_LIBRARY_PATH
        EOF
    - uses: ./.github/actions/build_and_test

  all_ci_tests:
    runs-on: ubuntu-22.04
    needs: [macos_build, ubuntu_build]
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
