name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_swiftformat

    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 

    - name: Ensure all packages have bzlformat checks
      shell: bash
      run: |
        bazelisk run //:bzlformat_missing_pkgs_test

    - name: Execute Integration Tests
      shell: bash
      run: |
        bazelisk test //:all_integration_tests

    - name: Test Simple Example with Poorly Formatted Code Change
      shell: bash
      run: |
        cd examples/simple
        cp main.swift main.swift.orig
        # The spaces at the front of the statement should be removed by the formatter.
        echo "     let bar = 2" >> main.swift
        # Format the Swift files and copy them back to the workspace
        bazelisk run //:update_all
        # This should succeed now that the formatted files have been updated
        bazelisk test //...
        # Revert the code change
        cp main.swift.orig main.swift

